task: 'cyberrunner_vision'
mirror_augment: false
steps: 5.01e5
env_num: 4
eval_every: 1e5
eval_episode_num: 10
action_repeat: 1
train_ratio: 512
time_limit: 2000

reward_every_n_waypoints: 3
hole_penalty: 1.0

seed: ${seed}
device: ${device}

size: [64, 64]
encoder:
  mlp_keys: 'states'
  cnn_keys: 'image'
decoder:
  mlp_keys: 'states'
  cnn_keys: 'image'
